### ISSUE TITLE
rendering isue JEI

### ISSUE THREAD

**Issue by BardGitH** [Tfarcenim/Enchanted-Book-Redesign#4]
![image](https://user-images.githubusercontent.com/57300546/68076129-239c5f00-fdb1-11e9-94d8-5026bc8edb4d.png)
when viewing books in JEI they only display one color of enchantment glimmer. Only EBR and JEI were installed on this instance.

**Comment by Tfarcenim** [comment]
remove optifine

**Comment by BardGitH** [comment]
There is no optifine installed. Hence why I mentioned only EBR and JEI were installed on the instance

**Comment by Tfarcenim** [comment]
quark seems to have the same issue, I don't even know if it's possible to fix

**Comment by Tfarcenim** [comment]
no longer an issue in 1.15
