### ISSUE TITLE
Crash on Login on Server with Quark

### ISSUE THREAD

**Issue by Divineaspect** [Tfarcenim/Enchanted-Book-Redesign#5]
this particular crash is wierdly complex because it involves the enchanted books in the hands of minecolonies mobs.
But looks to us like an intersection of this with quark.

https://pastebin.com/ApYtfGbh

**Comment by Vaelzan** [comment]
I believe the pull request that I submitted should fix this but it's up to the author of the mod to accept it and release an updated version.
