### ISSUE TITLE
[Request] Consider allowing Quark to overwrite enchanting colors

### ISSUE THREAD

**Issue by PeterBaker644** [Tfarcenim/Enchanted-Book-Redesign#8]
I love this mod! But it would be super cool if you use this alongside the runes from quark. Maybe if the quark tag is detected on an item, it defaults to the quark renderer? Just a thought. I love having my cake and eating it too.

**Comment by Spyro1502** [comment]
I agree with that, a solution would also be to have configuration to set if we want colored enchant, or a toggle for the different items categories

**Comment by FryoKnight** [comment]
Yeah, just noticed that the Quark Runes are pretty useless with his mod installed.
Kinda noticed it really dulls the enchantment effect one some items.

Some sort of config for this mod to just effect Enchantment Books only would be nice, but some sort of compatibility fix would be nice also.
